"use client";

import { Download, RefreshCw } from "lucide-react";
import { Fragment, useState } from "react";
import { DataState, Field, PageHeader, Panel, ProvenanceTag, StateBadge, ToneChip } from "@/components/hmi/primitives";
import { Button } from "@/components/ui/button";
import { api, type AuditEvent } from "@/lib/api";
import { fmt, fmtTime, humanize, useApi } from "@/lib/hmi";

function summary(e: AuditEvent): string {
  const x = e as Record<string, unknown>;
  switch (e.kind) {
    case "PREDICTION": return `prediction ${fmt(x.prediction as number, 1)} kg/h · model ${x.model ?? "—"}`;
    case "SCENARIO": return `${x.scenario_id} · fuel ${x.fuel_scenario} · price ${fmt(x.fuel_price_config as number, 0)} USD/t`;
    case "OPTIMIZATION": return `${x.recommendation_id} · ${x.optimizer} seed ${x.seed} budget ${x.budget} · ${humanize(String(x.recommendation_status))}`;
    case "OPERATOR_DECISION": return `${x.recommendation_id} → ${x.decision}${x.note ? ` (“${x.note}”)` : ""}`;
    case "DEMO_SCENE": return `scene ${x.scene_id}: ${x.title}`;
    default: return String(x.error ?? "");
  }
}

function download(name: string, data: unknown) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }));
  const a = Object.assign(document.createElement("a"), { href: url, download: name });
  a.click();
  URL.revokeObjectURL(url);
}

function EventsTable({ events, open, setOpen }: { events: AuditEvent[]; open: string | null; setOpen: (id: string | null) => void }) {
  return (
    <table className="w-full text-sm">
      <thead className="text-left text-[11px] uppercase tracking-wider text-muted-foreground">
        <tr><th className="py-1">Event</th><th>Time</th><th>Kind</th><th>Vessel</th><th>Trust</th><th>Summary</th><th><span className="sr-only">Details</span></th></tr>
      </thead>
      <tbody>
        {[...events].reverse().map((e) => {
          const x = e as Record<string, unknown>;
          const trust = x.trust as { state?: string } | undefined;
          return (
            <Fragment key={e.event_id}>
              <tr className="border-t align-top">
                <td className="num py-1.5 pr-2">{e.event_id}</td>
                <td className="num pr-2 text-xs">{fmtTime(e.timestamp)}</td>
                <td className="pr-2 text-xs font-semibold">{humanize(e.kind)}</td>
                <td className="pr-2 text-xs">{String(x.vessel_id ?? "—")}</td>
                <td className="pr-2">{trust?.state ? <StateBadge state={trust.state} /> : e.kind === "OPERATOR_DECISION" ? <ToneChip tone={x.decision === "ACCEPTED" ? "normal" : "ood"}>{String(x.decision)}</ToneChip> : "—"}</td>
                <td className="pr-2 text-xs">{summary(e)}</td>
                <td><Button size="sm" variant="ghost" aria-expanded={open === e.event_id} onClick={() => setOpen(open === e.event_id ? null : e.event_id)}>{open === e.event_id ? "Hide" : "Details"}</Button></td>
              </tr>
              {open === e.event_id && (
                <tr><td colSpan={7}><pre className="num max-h-80 overflow-auto rounded-md border bg-panel-2 p-2 text-[11px]">{JSON.stringify(e, null, 2)}</pre></td></tr>
              )}
            </Fragment>
          );
        })}
      </tbody>
    </table>
  );
}

export default function AuditPage() {
  const audit = useApi(api.audit, [], 15000);
  const [open, setOpen] = useState<string | null>(null);
  return (
    <>
      <PageHeader title="Audit / Reports"
        description="Decision records persisted by the API to a local SQLite ledger (append-only; not cryptographically sealed), kept separate from committed historical evidence. No history is generated by the frontend."
        actions={<Button variant="outline" onClick={audit.reload}><RefreshCw className="size-4" aria-hidden /> Refresh</Button>} />
      <DataState state={audit}>
        {(a) => {
          const h = a.historical;
          return (
            <div className="grid gap-3">
              <Panel title={<span className="flex items-center gap-2">Current session <ToneChip tone="info">CURRENT SESSION</ToneChip></span>} subtitle={a.session.label}
                actions={<Button size="sm" variant="outline" disabled={!a.session.events.length} onClick={() => download("egreen-quanta-session-audit.json", a.session)}><Download className="size-3.5" aria-hidden /> Export JSON</Button>}>
                {a.session.events.length === 0 ? (
                  <p className="text-sm text-muted-foreground">No events recorded yet in this session. Predictions, scenarios, optimizer runs, operator decisions and demo scenes appear here.</p>
                ) : <EventsTable events={a.session.events} open={open} setOpen={setOpen} />}
              </Panel>

              <Panel title={<span className="flex items-center gap-2">Prior sessions <ToneChip tone="demo">PERSISTED</ToneChip></span>}
                subtitle={`${a.persisted.label} · ${a.persisted.database} · ${a.persisted.total_events} events across ${a.persisted.total_sessions} session(s)`}>
                {a.persisted.events.length === 0
                  ? <p className="text-sm text-muted-foreground">No earlier sessions in the ledger.</p>
                  : <EventsTable events={a.persisted.events} open={open} setOpen={setOpen} />}
              </Panel>

              <div className="grid gap-3 xl:grid-cols-2">
                <Panel title={<span className="flex items-center gap-2">Release gate <ProvenanceTag kind="HISTORICAL" /></span>} subtitle={h.label}>
                  {h.release_gate ? (
                    <>
                      <dl className="mb-2">
                        <Field label="Classification" value={h.release_gate.classification ?? "—"} />
                        <Field label="Gates passed" value={`${h.release_gate.gates_passed} / ${h.release_gate.gates_evaluated}`} />
                        <Field label="Run timestamp" value={fmtTime(h.release_gate.timestamp_utc)} />
                      </dl>
                      <table className="w-full text-xs">
                        <tbody>
                          {h.release_gate.gates.map((g) => (
                            <tr key={g.id} className="border-t">
                              <td className="py-1 pr-2 font-medium">{g.id}</td>
                              <td className="pr-2"><ToneChip tone={g.status === "PASS" ? "normal" : "ood"}>{g.status}</ToneChip></td>
                              <td className="text-muted-foreground">{g.evidence ?? "unlabelled"}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </>
                  ) : <p className="text-sm text-muted-foreground">RELEASE/release_gate.json not found.</p>}
                </Panel>
                <div className="grid content-start gap-3">
                  <Panel title={<span className="flex items-center gap-2">Artifact integrity <ProvenanceTag kind="HISTORICAL" /></span>} subtitle="SHA-256 of files the API is serving from">
                    <dl>{h.artifacts.map((f) => <Field key={f.path} label={f.path} value={<span className="text-[11px]">{f.sha256.slice(0, 16)}…</span>} />)}</dl>
                  </Panel>
                  {h.claims && (
                    <Panel title={<span className="flex items-center gap-2">Claim ledger <ProvenanceTag kind="HISTORICAL" /></span>} subtitle={`${h.claims.verified_count} verified claims · prohibited claims below`}>
                      <div className="flex flex-wrap gap-1">{h.claims.prohibited.map((c) => <ToneChip key={c} tone="ood">{c}</ToneChip>)}</div>
                    </Panel>
                  )}
                </div>
              </div>
            </div>
          );
        }}
      </DataState>
    </>
  );
}
